production:
  adapter: mysql2
  database: indore_texi_production
  username: 
  password:  
  pool: 5

test:
  adapter: mysql2
  database: indore_texi_test
  username: 
  password:
  pool: 5

development:
  adapter: mysql2
  database: indore_texi_development
  username: 
  password:
  pool: 5
